# Generated by Django 4.2.1 on 2023-06-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_apellido_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
